export const adjectives = [
    { id: "adjective-1", word: "iyi", translation: "ভাল", partsOfSpeech: "Adjective" },
    { id: "adjective-2", word: "kötü", translation: "খারাপ", partsOfSpeech: "Adjective" },
    { id: "adjective-3", word: "büyük", translation: "বড়", partsOfSpeech: "Adjective" },
    { id: "adjective-4", word: "küçük", translation: "ছোট", partsOfSpeech: "Adjective" },
    { id: "adjective-5", word: "uzun", translation: "লম্বা", partsOfSpeech: "Adjective" },
    { id: "adjective-6", word: "kısa", translation: "খাটো", partsOfSpeech: "Adjective" },
    { id: "adjective-7", word: "yeni", translation: "নতুন", partsOfSpeech: "Adjective" },
    { id: "adjective-8", word: "eski", translation: "পুরাতন", partsOfSpeech: "Adjective" },
    { id: "adjective-9", word: "güzel", translation: "সুন্দর", partsOfSpeech: "Adjective" },
    { id: "adjective-10", word: "çirkin", translation: "কুৎসিত", partsOfSpeech: "Adjective" },
    { id: "adjective-11", word: "hızlı", translation: "দ্রুত", partsOfSpeech: "Adjective" },
    { id: "adjective-12", word: "yavaş", translation: "ধীরে", partsOfSpeech: "Adjective" },
    { id: "adjective-13", word: "zor", translation: "কঠিন", partsOfSpeech: "Adjective" },
    { id: "adjective-14", word: "kolay", translation: "সহজ", partsOfSpeech: "Adjective" },
    { id: "adjective-15", word: "zengin", translation: "ধনী", partsOfSpeech: "Adjective" },
    { id: "adjective-16", word: "fakir", translation: "গরিব", partsOfSpeech: "Adjective" },
    { id: "adjective-17", word: "temiz", translation: "পরিষ্কার", partsOfSpeech: "Adjective" },
    { id: "adjective-18", word: "kirli", translation: "নোংরা", partsOfSpeech: "Adjective" },
    { id: "adjective-19", word: "soğuk", translation: "ঠাণ্ডা", partsOfSpeech: "Adjective" },
    { id: "adjective-20", word: "sıcak", translation: "গরম", partsOfSpeech: "Adjective" },
    { id: "adjective-21", word: "dolu", translation: "পূর্ণ", partsOfSpeech: "Adjective" },
    { id: "adjective-22", word: "boş", translation: "খালি", partsOfSpeech: "Adjective" },
    { id: "adjective-23", word: "mutlu", translation: "খুশি", partsOfSpeech: "Adjective" },
    { id: "adjective-24", word: "üzgün", translation: "দুঃখিত", partsOfSpeech: "Adjective" },
    { id: "adjective-25", word: "yorgun", translation: "ক্লান্ত", partsOfSpeech: "Adjective" },
    { id: "adjective-26", word: "enerjik", translation: "উদ্যমী", partsOfSpeech: "Adjective" },
    { id: "adjective-27", word: "aç", translation: "ক্ষুধার্ত", partsOfSpeech: "Adjective" },
    { id: "adjective-28", word: "tok", translation: "পেটভরা", partsOfSpeech: "Adjective" },
    { id: "adjective-29", word: "akıllı", translation: "চতুর", partsOfSpeech: "Adjective" },
    { id: "adjective-30", word: "aptal", translation: "মূর্খ", partsOfSpeech: "Adjective" },
    { id: "adjective-31", word: "genç", translation: "তরুণ", partsOfSpeech: "Adjective" },
    { id: "adjective-32", word: "yaşlı", translation: "বৃদ্ধ", partsOfSpeech: "Adjective" },
    { id: "adjective-33", word: "hoş", translation: "আনন্দদায়ক", partsOfSpeech: "Adjective" },
    { id: "adjective-34", word: "kaba", translation: "রুক্ষ / অভদ্র", partsOfSpeech: "Adjective" },
    { id: "adjective-35", word: "doğru", translation: "সঠিক", partsOfSpeech: "Adjective" },
    { id: "adjective-36", word: "yanlış", translation: "ভুল", partsOfSpeech: "Adjective" },
    { id: "adjective-37", word: "meşgul", translation: "ব্যস্ত", partsOfSpeech: "Adjective" },
    { id: "adjective-38", word: "boş", translation: "ফাঁকা / অবসর", partsOfSpeech: "Adjective" },
    { id: "adjective-39", word: "kalın", translation: "মোটা", partsOfSpeech: "Adjective" },
    { id: "adjective-40", word: "ince", translation: "পাতলা", partsOfSpeech: "Adjective" },
    { id: "adjective-41", word: "sessiz", translation: "নীরব", partsOfSpeech: "Adjective" },
    { id: "adjective-42", word: "gürültülü", translation: "শব্দপূর্ণ", partsOfSpeech: "Adjective" },
    { id: "adjective-43", word: "yakın", translation: "কাছাকাছি", partsOfSpeech: "Adjective" },
    { id: "adjective-44", word: "uzak", translation: "দূর", partsOfSpeech: "Adjective" },
    { id: "adjective-45", word: "aynı", translation: "একই", partsOfSpeech: "Adjective" },
    { id: "adjective-46", word: "farklı", translation: "ভিন্ন", partsOfSpeech: "Adjective" },
    { id: "adjective-47", word: "sert", translation: "কঠিন / শক্ত", partsOfSpeech: "Adjective" },
    { id: "adjective-48", word: "yumuşak", translation: "নরম", partsOfSpeech: "Adjective" },
    { id: "adjective-49", word: "tatlı", translation: "মিষ্টি", partsOfSpeech: "Adjective" },
    { id: "adjective-50", word: "ekşi", translation: "টক", partsOfSpeech: "Adjective" }
  ]
  