export const verbs = [
    { id: "verb-1", word: "olmak", translation: "হওয়া", partsOfSpeech: "Verb" },
    { id: "verb-2", word: "yapmak", translation: "করা", partsOfSpeech: "Verb" },
    { id: "verb-3", word: "demek", translation: "বলা", partsOfSpeech: "Verb" },
    { id: "verb-4", word: "gitmek", translation: "যাওয়া", partsOfSpeech: "Verb" },
    { id: "verb-5", word: "gelmek", translation: "আসা", partsOfSpeech: "Verb" },
    { id: "verb-6", word: "almak", translation: "নেওয়া", partsOfSpeech: "Verb" },
    { id: "verb-7", word: "vermek", translation: "দেওয়া", partsOfSpeech: "Verb" },
    { id: "verb-8", word: "bilmek", translation: "জানা", partsOfSpeech: "Verb" },
    { id: "verb-9", word: "istemek", translation: "চাওয়া", partsOfSpeech: "Verb" },
    { id: "verb-10", word: "görmek", translation: "দেখা", partsOfSpeech: "Verb" },
    { id: "verb-11", word: "bulmak", translation: "খুঁজে পাওয়া", partsOfSpeech: "Verb" },
    { id: "verb-12", word: "söylemek", translation: "বলা", partsOfSpeech: "Verb" },
    { id: "verb-13", word: "kullanmak", translation: "ব্যবহার করা", partsOfSpeech: "Verb" },
    { id: "verb-14", word: "sevmek", translation: "ভালোবাসা", partsOfSpeech: "Verb" },
    { id: "verb-15", word: "anlamak", translation: "বুঝা", partsOfSpeech: "Verb" },
    { id: "verb-16", word: "düşünmek", translation: "ভাবা", partsOfSpeech: "Verb" },
    { id: "verb-17", word: "çalışmak", translation: "কাজ করা", partsOfSpeech: "Verb" },
    { id: "verb-18", word: "yaşamak", translation: "বাঁচা / বাস করা", partsOfSpeech: "Verb" },
    { id: "verb-19", word: "beklemek", translation: "অপেক্ষা করা", partsOfSpeech: "Verb" },
    { id: "verb-20", word: "konuşmak", translation: "কথা বলা", partsOfSpeech: "Verb" },
    { id: "verb-21", word: "açmak", translation: "খোলা", partsOfSpeech: "Verb" },
    { id: "verb-22", word: "kapatmak", translation: "বন্ধ করা", partsOfSpeech: "Verb" },
    { id: "verb-23", word: "başlamak", translation: "শুরু করা", partsOfSpeech: "Verb" },
    { id: "verb-24", word: "bitirmek", translation: "শেষ করা", partsOfSpeech: "Verb" },
    { id: "verb-25", word: "oturmak", translation: "বসা", partsOfSpeech: "Verb" },
    { id: "verb-26", word: "kalkmak", translation: "উঠা", partsOfSpeech: "Verb" },
    { id: "verb-27", word: "koşmak", translation: "দৌড়ানো", partsOfSpeech: "Verb" },
    { id: "verb-28", word: "yemek", translation: "খাওয়া", partsOfSpeech: "Verb" },
    { id: "verb-29", word: "içmek", translation: "পান করা", partsOfSpeech: "Verb" },
    { id: "verb-30", word: "öğrenmek", translation: "শেখা", partsOfSpeech: "Verb" },
    { id: "verb-31", word: "öğretmek", translation: "শেখানো", partsOfSpeech: "Verb" },
    { id: "verb-32", word: "aramak", translation: "খোঁজা / ফোন করা", partsOfSpeech: "Verb" },
    { id: "verb-33", word: "gezmek", translation: "ঘোরা", partsOfSpeech: "Verb" },
    { id: "verb-34", word: "taşımak", translation: "বহন করা", partsOfSpeech: "Verb" },
    { id: "verb-35", word: "uyumak", translation: "ঘুমানো", partsOfSpeech: "Verb" },
    { id: "verb-36", word: "uyanmak", translation: "ঘুম থেকে ওঠা", partsOfSpeech: "Verb" },
    { id: "verb-37", word: "gülmek", translation: "হাসা", partsOfSpeech: "Verb" },
    { id: "verb-38", word: "ağlamak", translation: "কাঁদা", partsOfSpeech: "Verb" },
    { id: "verb-39", word: "sormak", translation: "জিজ্ঞেস করা", partsOfSpeech: "Verb" },
    { id: "verb-40", word: "cevaplamak", translation: "উত্তর দেওয়া", partsOfSpeech: "Verb" },
    { id: "verb-41", word: "kapatmak", translation: "বন্ধ করা", partsOfSpeech: "Verb" },
    { id: "verb-42", word: "yardım etmek", translation: "সহায়তা করা", partsOfSpeech: "Verb" },
    { id: "verb-43", word: "temizlemek", translation: "পরিষ্কার করা", partsOfSpeech: "Verb" },
    { id: "verb-44", word: "yazmak", translation: "লিখা", partsOfSpeech: "Verb" },
    { id: "verb-45", word: "okumak", translation: "পড়া", partsOfSpeech: "Verb" },
    { id: "verb-46", word: "taşınmak", translation: "স্থানান্তর হওয়া", partsOfSpeech: "Verb" },
    { id: "verb-47", word: "çizmek", translation: "আঁকা", partsOfSpeech: "Verb" },
    { id: "verb-48", word: "çıkmak", translation: "বের হওয়া", partsOfSpeech: "Verb" }
  ]
  